application: causal-scarab-704
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(html))
  static_files: static/html/\1
  upload: static/html/(.*\.(html))
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /js
  static_dir: static/js
- url: /json
  static_dir: static/json
- url: .*
  script: django_project_settings.wsgi.application

libraries:
- name: django
  version: 1.5
- name: numpy
  version: latest


skip_files:
- ^ETL$
- ^(.*/)?\.pyc$
